stages:
  - build
  - security
  - quality

# Job del SonarCloud
sonarcloud_scan:
  stage: quality
  image: sonarsource/sonar-scanner-cli:latest

  script:
    - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=$SONAR_HOST_URL
    # Crear artifact que indica que el análisis finalizó
    - echo '{"tool":"SonarCloud","status":"analysis_completed"}' > $CI_PROJECT_DIR/Artifact_Desarrollo_Seguro.json

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/Artifact_Desarrollo_Seguro.json

# Job del Dependency Check
dependency_check:
  stage: security
  image: ubuntu:22.04
  before_script:
    # Instalar jq y curl
    - apt-get update && apt-get install -y curl jq default-jre-headless unzip

  script:
    # Descargar Dependency Check CLI si no está disponible
    - if [ ! -d "/opt/dependency-check" ]; then \
        curl -L -o /tmp/dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.1/dependency-check-8.3.1-release.zip && \
        unzip /tmp/dependency-check.zip -d /opt && mv /opt/dependency-check-8.3.1 /opt/dependency-check; \
      fi

    # Ejecutar el análisis
    - /opt/dependency-check/dependency-check.sh \
        --project "H4ck1ng" \
        --scan $CI_PROJECT_DIR \
        --format JSON \
        --prettyPrint \
        --out $CI_PROJECT_DIR

    # Generar artifact y bloquear pipeline si hay vulnerabilidades críticas, altas o medias
    - |
      if [ -f "$CI_PROJECT_DIR/dependency-check-report.json" ]; then
        mv "$CI_PROJECT_DIR/dependency-check-report.json" "$CI_PROJECT_DIR/Artifact_Desarrollo_Seguro.json"
        CRITICAL_COUNT=$(jq '[.dependencies[].vulnerabilities[]?.severity] | map(select(.=="Critical" or .=="High" or .=="Medium")) | length' $CI_PROJECT_DIR/Artifact_Desarrollo_Seguro.json)
        if [ "$CRITICAL_COUNT" -gt 0 ]; then
          echo "¡Se han encontrado vulnerabilidades críticas, altas o medias!"
          exit 1
        fi
      else
        echo '{"tool":"DependencyCheck","status":"report_not_generated"}' > "$CI_PROJECT_DIR/Artifact_Desarrollo_Seguro.json"
      fi

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/Artifact_Desarrollo_Seguro.json

  # Para pruebas completas sin bloquear pipeline, se puede usar:
  # allow_failure: true